import os
from PIL import Image
import numpy as np

# ========== CONFIGURATION ==========
INPUT_FOLDER = "."  # Folder where your frame_0001.png files are
OUTPUT_FILE = "video_frames.h"  # Output header file for Arduino
FRAME_PREFIX = "frame"  # Prefix for array names
TARGET_WIDTH = 128  # OLED width
TARGET_HEIGHT = 64   # OLED height
# ===================================

def image_to_byte_array(image_path):
    """Convert an image to a byte array for monochrome OLED display"""
    
    # Open and convert image
    img = Image.open(image_path)
    
    # Convert to RGB if needed, then to grayscale, then to 1-bit (black/white)
    if img.mode != 'RGB':
        img = img.convert('RGB')
    
    # Resize to target dimensions
    img = img.resize((TARGET_WIDTH, TARGET_HEIGHT), Image.Resampling.LANCZOS)
    
    # Convert to grayscale
    gray = img.convert('L')
    
    # Convert to black and white (threshold at 127)
    # Pixel > 127 becomes white (1), <= 127 becomes black (0)
    bw = gray.point(lambda p: 1 if p > 127 else 0, mode='1')
    
    # Pack 8 pixels into 1 byte (horizontal packing for Adafruit_GFX)
    byte_array = []
    for y in range(TARGET_HEIGHT):
        for x in range(0, TARGET_WIDTH, 8):
            byte = 0
            for bit in range(8):
                if x + bit < TARGET_WIDTH:
                    # Get pixel value (0 or 1)
                    pixel = bw.getpixel((x + bit, y))
                    if pixel == 1:  # White pixel
                        byte |= (1 << (7 - bit))  # MSB first
            byte_array.append(byte)
    
    return byte_array

def generate_c_array(array_data, array_name):
    """Generate C++ array declaration from byte array"""
    
    # Format bytes as hex, 16 per line
    lines = []
    for i in range(0, len(array_data), 16):
        chunk = array_data[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'  {hex_bytes}')
    
    array_content = ',\n'.join(lines)
    
    return f'''static const unsigned char PROGMEM {array_name}[] = {{
{array_content}
}};
'''

def main():
    # Get all PNG files matching frame_*.png pattern
    frame_files = sorted([f for f in os.listdir(INPUT_FOLDER) 
                          if f.startswith('frame_') and f.endswith('.png')])
    
    if not frame_files:
        print("No frame files found! Make sure your PNG files are in the current directory.")
        print("Looking for files starting with 'frame_' and ending with '.png'")
        return
    
    print(f"Found {len(frame_files)} frames to convert")
    
    # Generate arrays for each frame
    all_arrays = []
    frame_pointers = []
    
    for i, filename in enumerate(frame_files, 1):
        print(f"Processing {filename} ({i}/{len(frame_files)})...")
        filepath = os.path.join(INPUT_FOLDER, filename)
        array_name = f"{FRAME_PREFIX}{i}"
        
        # Convert image to byte array
        byte_data = image_to_byte_array(filepath)
        
        # Generate C array
        array_code = generate_c_array(byte_data, array_name)
        all_arrays.append(array_code)
        frame_pointers.append(array_name)
    
    # Create the complete header file
    with open(OUTPUT_FILE, 'w') as f:
        f.write("// Auto-generated video frames for OLED display\n")
        f.write("// Generated by convert_frames.py\n\n")
        
        # Write all frame arrays
        for array_code in all_arrays:
            f.write(array_code)
            f.write("\n")
        
        # Write frames array pointer list
        f.write("// Array of pointers to all frames\n")
        f.write(f"static const unsigned char* const PROGMEM FRAMES[] = {{\n")
        for ptr in frame_pointers:
            f.write(f"  {ptr},\n")
        f.write("};\n\n")
        
        # Write frame count constant
        f.write(f"const int TOTAL_FRAMES = {len(frame_files)};\n")
    
    print(f"\n✅ Done! Created {OUTPUT_FILE} with {len(frame_files)} frames")
    print(f"\nUsage in Arduino sketch:")
    print(f"#include \"{OUTPUT_FILE}\"")
    print(f"\n// Then in your code:")
    print(f"for (int i = 0; i < TOTAL_FRAMES; i++) {{")
    print(f"    display.drawBitmap(0, 0, FRAMES[i], 128, 64, WHITE);")
    print(f"    display.display();")
    print(f"    delay(66); // ~15 fps")
    print(f"}}")

if __name__ == "__main__":
    main()